version: '3.7'
services:
  wishlist:
    image: miguel/wishlist:latest
    container_name: wishlist
    networks:
      - local
    depends_on:
      - dynamodb-local
      - redis
    ports:
      - "8080:8080"

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-wishlist
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"
    networks:
      - local

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local

networks:
  local:
    driver: bridge